version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Add root username here
      - MONGO_INITDB_ROOT_PASSWORD=rootpass  # Add root password here
      - MONGO_INITDB_DATABASE=amazon         # Your database name
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root  # MongoDB root username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass  # MongoDB root password
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin     # Database for authentication (usually 'admin')
    depends_on:
      - mongo
    ports:
      - 8081:8081
